f=open('rotator.html','r')
h=f.read()
f.close()
h=h.replace('<strong style="color:#fff">Not sure','<strong style="color:#4ECDC4">Not sure')
h=h.replace('<strong style="color:#fff">generic','<strong style="color:#4ECDC4">generic')
h=h.replace('<strong style="color:#fff">${select','<strong style="color:#1A1A2E">${select')
open('rotator.html','w').write(h)
print('done')