f=open('readlead.html','r')
h=f.read()
f.close()
i=h.find('function showProg(id)')
j=h.find('function bldGroups()')
old=h[i:j]
new='function showProg(id){\n'
new+='var stu=students.find(function(s){return s.id===id;});\n'
new+='cur=stu;\n'
new+='document.getElementById("prog-h").textContent=stu.name+": Reading Profile";\n'
new+='document.getElementById("prog-sub").innerHTML=tag(stu.level,lc(stu.level))+" "+lb(stu.level)+" - "+stu.grade+" - "+stu.sessions.length+" sessions";\n'
new+='var sess=stu.sessions||[];\n'
new+='if(!sess.length){\n'
new+='document.getElementById("prog-out").innerHTML="<div class=\'card\' style=\'text-align:center;padding:40px\'><div style=\'font-size:36px;margin-bottom:10px\'>No sessions yet</div><button class=\'btn\' onclick=\'startSess("+stu.id+")\'>Start First Session</button></div>";\n'
new+='go("progress");return;\n'
new+='}\n'
new+='var latest=sess[0].ratings||{};\n'
new+='var QRL=[{id:"accuracy",l:"Accuracy",c:"#FF6B6B"},{id:"fluency",l:"Fluency",c:"#FFD166"},{id:"decoding",l:"Decoding",c:"#FF9F43"},{id:"selfmon",l:"Self-Monitoring",c:"#4ECDC4"},{id:"comprehension",l:"Comprehension",c:"#A78BFA"}];\n'
new+='var strengths=QRL.filter(function(r){return(latest[r.id]||0)>=85;});\n'
new+='var growth=QRL.filter(function(r){return(latest[r.id]||0)<75;});\n'
new+='var html="";\n'
new+='html+="<div class=\'grid2\' style=\'margin-bottom:12px\'>";\n'
new+='html+="<div class=\'card\' style=\'border-top:4px solid #4ECDC4\'><div style=\'font-size:12px;font-weight:800;color:#999;margin-bottom:8px\'>STRENGTHS</div>";\n'
new+='if(strengths.length){html+=strengths.map(function(r){return"<div style=\'display:flex;align-items:center;gap:6px;margin-bottom:4px\'><div style=\'width:8px;height:8px;border-radius:50%;background:"+r.c+"\'></div><div style=\'font-size:13px;font-weight:600\'>"+r.l+"</div><div style=\'font-size:12px;color:#888;margin-left:auto\'>"+(latest[r.id]||0)+"%</div></div>";}).join("");}else{html+="<div style=\'font-size:13px;color:#AAA\'>Complete more sessions to identify strengths</div>";}\n'
new+='html+="</div>";\n'
new+='html+="<div class=\'card\' style=\'border-top:4px solid #FF6B6B\'><div style=\'font-size:12px;font-weight:800;color:#999;margin-bottom:8px\'>FOCUS AREAS</div>";\n'
new+='if(growth.length){html+=growth.map(function(r){return"<div style=\'display:flex;align-items:center;gap:6px;margin-bottom:4px\'><div style=\'width:8px;height:8px;border-radius:50%;background:"+r.c+"\'></div><div style=\'font-size:13px;font-weight:600\'>"+r.l+"</div><div style=\'font-size:12px;color:#888;margin-left:auto\'>"+(latest[r.id]||0)+"%</div></div>";}).join("");}else{html+="<div style=\'font-size:13px;color:#AAA\'>No significant areas of concern</div>";}\n'
new+='html+="</div></div>";\n'
new+='html+="<div class=\'card\' style=\'margin-bottom:12px\'><div style=\'font-size:14px;font-weight:700;margin-bottom:12px\'>Skill Ratings</div>";\n'
new+='QRL.forEach(function(r){\n'
new+='var vals=sess.map(function(s){return s.ratings&&s.ratings[r.id]?s.ratings[r.id]:null;}).filter(function(v){return v!==null;}).slice(0,5).reverse();\n'
new+='var curr=vals[vals.length-1]||0;\n'
new+='var prev=vals.length>1?vals[vals.length-2]:null;\n'
new+='var diff=prev!==null?curr-prev:null;\n'
new+='var c=curr>=90?"#6BCB77":curr>=75?"#FFD166":"#FF6B6B";\n'
new+='html+="<div style=\'margin-bottom:14px\'><div style=\'display:flex;justify-content:space-between;align-items:center;margin-bottom:4px\'>";\n'
new+='html+="<div style=\'font-size:13px;font-weight:600\'>"+r.l+"</div>";\n'
new+='html+="<div style=\'display:flex;align-items:center;gap:6px\'>";\n'
new+='if(diff!==null&&diff!==0)html+="<div style=\'font-size:11px;font-weight:800;color:"+(diff>0?"#6BCB77":"#FF6B6B")+"\'>"+(diff>0?"+":"")+diff+"</div>";\n'
new+='html+="<div style=\'font-size:15px;font-weight:800;color:"+c+"\'>"+curr+"%</div></div></div>";\n'
new+='html+="<div class=\'pbg\'><div class=\'pbar\' style=\'width:"+curr+"%;background:"+c+"\'></div></div>";\n'
new+='if(vals.length>1){\n'
new+='html+="<div style=\'display:flex;gap:4px;margin-top:4px\'>";\n'
new+='vals.forEach(function(v,vi){\n'
new+='var vc=v>=90?"#6BCB77":v>=75?"#FFD166":"#FF6B6B";\n'
new+='html+="<div style=\'flex:1;background:#F5F3EE;border-radius:4px;padding:2px 0;text-align:center\'><div style=\'height:3px;background:"+vc+";border-radius:2px;width:"+v+"%\'></div><div style=\'font-size:9px;color:#AAA;margin-top:1px\'>S"+(vi+1)+"</div></div>";\n'
new+='});\n'
new+='html+="</div>";\n'
new+='}\n'
new+='html+="</div>";\n'
new+='});\n'
new+='html+="</div>";\n'
new+='if(sess[0].errors&&sess[0].errors.length){\n'
new+='html+="<div class=\'card\' style=\'margin-bottom:12px\'><div style=\'font-size:14px;font-weight:700;margin-bottom:10px\'>Recent Errors</div>";\n'
new+='html+=sess[0].errors.map(function(e){return"<div style=\'display:flex;align-items:center;gap:8px;padding:6px 0;border-bottom:1px solid #F5F3EE\'><span style=\'font-weight:700;font-size:13px\'>"+e.word+"</span>"+(e.said?"<span style=\'font-size:12px;color:#888\'>said "+e.said+"</span>":"")+"<span style=\'font-size:11px;background:#FF9F4322;color:#FF9F43;border-radius:20px;padding:2px 8px;font-weight:700;margin-left:auto\'>"+e.type+"</span></div>";}).join("");\n'
new+='html+="</div>";\n'
new+='}\n'
new+='html+="<div class=\'card\'><div style=\'font-size:14px;font-weight:700;margin-bottom:12px\'>Session History</div>";\n'
new+='html+=sess.map(function(s,i){return"<div style=\'padding:10px 0;border-bottom:"+(i<sess.length-1?"1px solid #F5F3EE":"none")+"\'><div style=\'display:flex;justify-content:space-between;margin-bottom:6px\'><span style=\'font-weight:700;font-size:13px\'>"+s.date+"</span>"+tag(i===0?"Latest":"Session "+(sess.length-i),"#DDD")+"</div><div style=\'display:flex;flex-wrap:wrap;gap:5px\'>"+QRL.map(function(r){var v=s.ratings&&s.ratings[r.id]?s.ratings[r.id]:0;var c=v>=90?"#6BCB77":v>=75?"#FFD166":"#FF6B6B";return"<span style=\'font-size:11px;background:"+c+"22;color:"+c+";border-radius:6px;padding:2px 7px;font-weight:700\'>"+r.l+" "+v+"%</span>";}).join("")+"</div></div>";}).join("");\n'
new+='html+="</div>";\n'
new+='html+="<div style=\'display:flex;gap:10px;margin-top:12px\'>";\n'
new+='html+="<button class=\'btn\' onclick=\'startSess("+stu.id+")\' style=\'flex:1\'>Start New Session</button>";\n'
new+='html+="<button class=\'btn btn-purple\' onclick=\'window.location=\\\"progress.html\\\"\' style=\'flex:1\'>Generate Report</button>";\n'
new+='html+="</div>";\n'
new+='document.getElementById("prog-out").innerHTML=html;\n'
new+='go("progress");\n'
new+='}\n'
h=h[:i]+new+h[j:]
open('readlead.html','w').write(h)
print('done')