f=open('progress.html','a')
f.write('async function doGen(){\n')
f.write('if(!cur)return;\n')
f.write('var sessions=cur.sessions||[];\n')
f.write('var period=document.getElementById("rep-period").value;\n')
f.write('var notes=document.getElementById("extra-notes").value.trim();\n')
f.write('var latest=sessions[0]||{};\n')
f.write('var rats=latest.ratings||{};\n')
f.write('var rStr=QR.map(function(r){var v=rats[r.id]||75;var level=v>=90?"strong":v>=75?"developing":"needs support";return r.l+": "+v+"% ("+level+")";}).join(", ");\n')
f.write('var trend="";\n')
f.write('if(sessions.length>=2){\n')
f.write('var prev=sessions[1].ratings||{};\n')
f.write('var improvements=QR.filter(function(r){return(rats[r.id]||75)>(prev[r.id]||75);}).map(function(r){return r.l;});\n')
f.write('if(improvements.length)trend="Showing improvement in: "+improvements.join(", ")+".";\n')
f.write('}\n')
f.write('var outcomes=selectedOutcomes.length?selectedOutcomes.join("; "):"General reading development";\n')
f.write('var prompt="You are an experienced teacher writing formal report card comments.\\n";\n')
f.write('prompt+="Student: "+cur.name+"\\n";\n')
f.write('prompt+="Grade: "+cur.grade+"\\n";\n')
f.write('prompt+="Reading Level: "+cur.level+"\\n";\n')
f.write('prompt+="Reporting Period: "+period+"\\n";\n')
f.write('prompt+="Reading Assessment Data: "+rStr+"\\n";\n')
f.write('if(trend)prompt+="Progress Trend: "+trend+"\\n";\n')
f.write('prompt+="Curriculum Outcomes to Address: "+outcomes+"\\n";\n')
f.write('if(notes)prompt+="Teacher Notes: "+notes+"\\n";\n')
f.write('prompt+="\\nGenerate 3 report card comment options. Each should be 3-4 sentences, professional, positive, specific to the data, include a strength and next step.\\n";\n')
f.write('prompt+="Reply ONLY with raw JSON: {\\"comments\\":[{\\"label\\":\\"Strength Focus\\",\\"text\\":\\"...\\"},{\\"label\\":\\"Growth Focus\\",\\"text\\":\\"...\\"},{\\"label\\":\\"Balanced\\",\\"text\\":\\"...\\"}]}";\n')
f.write('document.getElementById("gen-box").innerHTML="<div style=\'text-align:center;padding:16px\'><div style=\'font-size:14px;font-weight:700;color:#A78BFA\'>Generating comments for "+cur.name+"...</div></div>";\n')
f.write('document.getElementById("comments-out").innerHTML="";\n')
f.write('try{\n')
f.write('var res=await fetch("/api/lesson",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({model:"claude-sonnet-4-5",max_tokens:2000,messages:[{role:"user",content:prompt}]})});\n')
f.write('var data=await res.json();\n')
f.write('var text=(data.content||[]).filter(function(b){return b.type==="text";}).map(function(b){return b.text;}).join("").trim();\n')
f.write('var parsed;\n')
f.write('try{parsed=JSON.parse(text);}catch(e){var a=text.indexOf("{"),b=text.lastIndexOf("}");parsed=JSON.parse(text.slice(a,b+1));}\n')
f.write('var comments=parsed.comments||[];\n')
f.write('var html="";\n')
f.write('comments.forEach(function(c,ci){\n')
f.write('html+="<div class=\'comment-box\'>";\n')
f.write('html+="<div style=\'font-size:11px;font-weight:800;color:#A78BFA;margin-bottom:8px\'>"+c.label+"</div>";\n')
f.write('html+="<div style=\'font-size:14px;line-height:1.7;margin-bottom:28px\' id=\'ct-"+ci+"\'>"+c.text+"</div>";\n')
f.write('html+="<button class=\'copy-btn\' onclick=\'copyText("+ci+")\'>Copy</button>";\n')
f.write('html+="</div>";\n')
f.write('});\n')
f.write('document.getElementById("comments-out").innerHTML=html;\n')
f.write('document.getElementById("gen-box").innerHTML="<div style=\'font-size:14px;font-weight:800;color:#A78BFA;margin-bottom:8px\'>Comments Generated!</div><button class=\'btn btn-purple\' style=\'width:100%;font-size:14px\' onclick=\'doGen()\'>Regenerate</button>";\n')
f.write('}catch(e){\n')
f.write('document.getElementById("gen-box").innerHTML="<div style=\'font-size:15px;font-weight:800;margin-bottom:4px\'>Generate Report Comments</div><div style=\'font-size:12px;color:#FF6B6B;margin-bottom:14px\'>Error: "+e.message+"</div><button class=\'btn btn-purple\' style=\'width:100%;font-size:14px\' onclick=\'doGen()\'>Try Again</button>";\n')
f.write('}\n')
f.write('}\n')
f.write('function copyText(i){\n')
f.write('var el=document.getElementById("ct-"+i);\n')
f.write('navigator.clipboard.writeText(el.textContent).then(function(){\n')
f.write('var btn=el.nextElementSibling;\n')
f.write('btn.textContent="Copied!";\n')
f.write('setTimeout(function(){btn.textContent="Copy";},2000);\n')
f.write('});\n')
f.write('}\n')
f.write('rdHome();\n')
f.write('</script>\n')
f.write('</body>\n')
f.write('</html>\n')
f.close()
print('progress reporter complete!')